### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Croma - Palette Manager
email: admin@croma.app
description: Croma - Palette Manager - Get ideas for colors on the go
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://croma.app" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
twitter_username: kamalkishor1991
github_username:  croma-app
author: Kamal
logo: assets/images/large-logo.png
twitter:
  username: kamalkishor1991
social:
  name: Sandoche Adittane
  links:
    - https://twitter.com/kamalkishor1991
    - https://github.com/croma-app

languages: ["en"]
ampdir: amp

github: https://github.com/croma-app/croma-react

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
google_analytics: G-P9VYCZPJQW
ad_tracking_tag: AW-834081170
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
include:
  - ".well-known"
