name: Croma - Palette Manager
description: Save your colors on the go
full_description: 'Croma is a simple color palette manager and color picker made for designers, aiming to make it quick and fun to create and share color palettes on the go.
<br>

### Key features ###<br><br>

• Automatically extract prominent colors from an image from your gallery or camera with our unique algorithm. <br>
• Manually pick any number of colors in an object with your camera. <br>
• Manually pick any number of colors from images.<br>
• Recognize and save hex color codes in the text using your camera.<br>
• Generate palettes with various color models such as complementary, split-complementary, triadic, tetradic, analogous, monochromatic etc. <br>
• Share palettes with a link for quick preview. <br>
• View various information about a color and convert to other color codes. <br>
• Copy color codes to your clipboard with a tap. <br>
• Add colors using various color code formats including CSS named colors. <br>
• Material design palettes <br>'
android: https://play.google.com/store/apps/details?id=app.croma
iOS: https://apps.apple.com/app/croma-palette-manager/id1596763657
web: https://web.croma.app/
screenshots:
  - 2.png
  - 4.png
  - 5.png
  - 6.png
  - 7.png
  - 8.png
  - 9.png
producthunt: https://www.producthunt.com/posts/croma
companies:

